#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cargo clippy
cargo install --git https://github.com/semantic-rs/semantic-rs --debug &&
      export PATH=$HOME/.cargo/bin:$PATH &&
      git config --global user.name semantic-rs &&
      git config --global user.email semantic@rs